import SwiftUI
import SwiftData

/// Workout hub: planned workouts generated by the app, plus recent real
/// activity from Apple Health (including Watch sessions).
struct WorkoutTabView: View {
    @Query(sort: \GeneratedWorkout.createdAt, order: .reverse) private var workouts: [GeneratedWorkout]
    @Query private var journalEntries: [WorkoutJournalEntry]
    @State private var history: WorkoutHistoryModel
    @State private var selectedWorkout: GeneratedWorkout?
    @State private var selectedHealthWorkout: WorkoutSummary?
    @State private var isCoachPresented = false

    init(history: WorkoutHistoryModel = WorkoutHistoryModel()) {
        _history = State(initialValue: history)
    }

    var body: some View {
        NavigationStack {
            Group {
                if workouts.isEmpty && history.recentWorkouts.isEmpty {
                    ContentUnavailableView(
                        "No Workouts Yet",
                        systemImage: "figure.run",
                        description: Text("Choose today’s workout from Path, or start one on your Watch.")
                    )
                } else {
                    List {
                        if !workouts.isEmpty {
                            Section("Planned") {
                                ForEach(workouts) { workout in
                                    Button {
                                        selectedWorkout = workout
                                    } label: {
                                        plannedRow(workout)
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                        }
                        if !history.recentWorkouts.isEmpty {
                            Section("Recent Activity") {
                                ForEach(history.recentWorkouts) { summary in
                                    Button {
                                        selectedHealthWorkout = summary
                                    } label: {
                                        HealthWorkoutRow(
                                            summary: summary,
                                            journalEntry: journalEntries.first {
                                                $0.workoutID == summary.id
                                            }
                                        )
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                        }
                    }
                }
            }
            .navigationTitle("Workouts")
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button {
                        isCoachPresented = true
                    } label: {
                        Label("Ask Coach", systemImage: "bubble.left.and.text.bubble.right")
                    }
                }
            }
            .task {
                await history.refresh()
            }
            .refreshable {
                await history.refresh()
            }
            .sheet(item: $selectedWorkout) { workout in
                WorkoutDetailView(workout: workout)
            }
            .sheet(item: $selectedHealthWorkout) { summary in
                HealthWorkoutJournalView(
                    summary: summary,
                    existingEntry: journalEntries.first {
                        $0.workoutID == summary.id
                    }
                )
            }
            .sheet(isPresented: $isCoachPresented) {
                CoachView()
            }
        }
    }

    private func plannedRow(_ workout: GeneratedWorkout) -> some View {
        HStack(spacing: BPSpacing.medium) {
            VStack(alignment: .leading, spacing: BPSpacing.xSmall) {
                Text(workout.title)
                    .font(.body.weight(.medium))
                Text(workout.createdAt.formatted(date: .abbreviated, time: .shortened))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            if workout.completedAt != nil {
                Image(systemName: "checkmark.circle.fill")
                    .foregroundStyle(.green)
                    .accessibilityLabel("Completed")
            }
        }
        .padding(.vertical, BPSpacing.xSmall)
    }

}

private struct HealthWorkoutRow: View {
    let summary: WorkoutSummary
    let journalEntry: WorkoutJournalEntry?

    var body: some View {
        HStack(spacing: BPSpacing.medium) {
            VStack(alignment: .leading, spacing: BPSpacing.xSmall) {
                if let customName = journalEntry?.customName {
                    Text(customName)
                        .font(.body.weight(.medium))
                } else if let activity = summary.activity {
                    Text(activity.displayName)
                        .font(.body.weight(.medium))
                } else {
                    Text("Workout")
                        .font(.body.weight(.medium))
                }
                Text(summary.start, format: .dateTime.day().month().year().hour().minute())
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: BPSpacing.xSmall) {
                if journalEntry?.isFavorite == true {
                    Image(systemName: "star.fill")
                        .foregroundStyle(BodyPilotColors.warningOrange)
                        .accessibilityLabel("Favorite")
                }
                Text("\(Int(summary.durationMinutes.rounded())) min")
                    .font(.subheadline)
                if let effort = journalEntry?.perceivedExertion {
                    Text("RPE \(effort)")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                } else if let energy = summary.totalEnergyKilocalories {
                    Text("\(Int(energy.rounded())) kcal")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
            }
        }
        .padding(.vertical, BPSpacing.xSmall)
    }
}

#Preview {
    WorkoutTabView(history: WorkoutHistoryModel(healthMetrics: MockHealthProvider()))
        .modelContainer(for: [GeneratedWorkout.self, WorkoutJournalEntry.self], inMemory: true)
}
