import SwiftUI
import SwiftData

/// Workout hub: planned workouts generated by the app, plus recent real
/// activity from Apple Health (including Watch sessions).
struct WorkoutTabView: View {
    @Query(sort: \GeneratedWorkout.createdAt, order: .reverse) private var workouts: [GeneratedWorkout]
    @State private var history: WorkoutHistoryModel
    @State private var selectedWorkout: GeneratedWorkout?

    init(history: WorkoutHistoryModel = WorkoutHistoryModel()) {
        _history = State(initialValue: history)
    }

    var body: some View {
        NavigationStack {
            Group {
                if workouts.isEmpty && history.recentWorkouts.isEmpty {
                    ContentUnavailableView(
                        "No Workouts Yet",
                        systemImage: "figure.run",
                        description: Text("Generate today's workout from the Today tab, or start one on your Watch.")
                    )
                } else {
                    List {
                        if !workouts.isEmpty {
                            Section("Planned") {
                                ForEach(workouts) { workout in
                                    Button {
                                        selectedWorkout = workout
                                    } label: {
                                        plannedRow(workout)
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                        }
                        if !history.recentWorkouts.isEmpty {
                            Section("Recent Activity") {
                                ForEach(history.recentWorkouts, id: \.self) { summary in
                                    healthRow(summary)
                                }
                            }
                        }
                    }
                }
            }
            .navigationTitle("Workout")
            .task {
                await history.refresh()
            }
            .refreshable {
                await history.refresh()
            }
            .sheet(item: $selectedWorkout) { workout in
                WorkoutDetailView(workout: workout)
            }
        }
    }

    private func plannedRow(_ workout: GeneratedWorkout) -> some View {
        HStack(spacing: BPSpacing.medium) {
            VStack(alignment: .leading, spacing: BPSpacing.xSmall) {
                Text(workout.title)
                    .font(.body.weight(.medium))
                Text(workout.createdAt.formatted(date: .abbreviated, time: .shortened))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            if workout.completedAt != nil {
                Image(systemName: "checkmark.circle.fill")
                    .foregroundStyle(.green)
                    .accessibilityLabel("Completed")
            }
        }
        .padding(.vertical, BPSpacing.xSmall)
    }

    private func healthRow(_ summary: WorkoutSummary) -> some View {
        HStack(spacing: BPSpacing.medium) {
            VStack(alignment: .leading, spacing: BPSpacing.xSmall) {
                if let activity = summary.activity {
                    Text(activity.displayName)
                        .font(.body.weight(.medium))
                } else {
                    Text("Workout")
                        .font(.body.weight(.medium))
                }
                Text(summary.start.formatted(date: .abbreviated, time: .shortened))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: BPSpacing.xSmall) {
                Text("\(Int(summary.durationMinutes.rounded())) min")
                    .font(.subheadline)
                if let energy = summary.totalEnergyKilocalories {
                    Text("\(Int(energy.rounded())) kcal")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
            }
        }
        .padding(.vertical, BPSpacing.xSmall)
    }
}

#Preview {
    WorkoutTabView(history: WorkoutHistoryModel(healthMetrics: MockHealthProvider()))
        .modelContainer(for: GeneratedWorkout.self, inMemory: true)
}
