import SwiftUI

/// Spacing scale shared by iPhone and Watch layouts.
enum BPSpacing {
    static let xSmall: CGFloat = 4
    static let small: CGFloat = 8
    static let medium: CGFloat = 16
    static let large: CGFloat = 24
    static let xLarge: CGFloat = 32
}

/// Corner radii for cards and controls.
enum BPCornerRadius {
    static let card: CGFloat = 16
    static let control: CGFloat = 12
}

/// Semantic palette for the premium rebuild screens.
enum BodyPilotColors {
    static let background = Color(hex: 0xF7F7FA)
    static let card = Color.white
    static let primaryText = Color(hex: 0x111111)
    static let secondaryText = Color(hex: 0x6E6E73)
    static let accentOrange = Color(hex: 0xFF6F32)
    static let sleepIndigo = Color(hex: 0x5755D9)
    static let sleepLavender = Color(hex: 0xE9E8FF)
    static let successGreen = Color(hex: 0x2FCB92)
    static let warningOrange = Color(hex: 0xFF7B3A)
    static let remBlue = Color(hex: 0x69B7F7)
    static let coreBlue = Color(hex: 0x4A82E8)
    static let deepPurple = Color(hex: 0x6C3CCB)
    static let landscapeBlue = Color(hex: 0xD7E8F7)
    static let warmGlow = Color(hex: 0xFFF1DD)
}

enum BodyPilotAsset {
    static let onboardingWelcome = "onboarding_welcome"
    static let onboardingMeet = "onboarding_meet"
    static let onboardingLearn = "onboarding_learn"
    static let onboardingName = "onboarding_name"
    static let onboardingHealth = "onboarding_health"
    static let onboardingWatch = "onboarding_watch"
    static let onboardingReminders = "onboarding_reminders"
    static let onboardingCoach = "onboarding_coach"
    static let onboardingReady = "onboarding_ready"
    static let onboardingPremium = "onboarding_premium"

    static let sleepDeepArticle = "sleep_deep_article"
    static let sleepConsistencyArticle = "sleep_consistency_article"
    static let sleepGoal = "sleep_goal"
}

private extension Color {
    init(hex: UInt, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

// Brand palette colors (Color.pilotBlue, .routeTeal, .deepBlue, .skyMist,
// .graphite, .coolGray, .brandLightGray, .brandWhite) are auto-generated by
// Xcode from the asset catalogs in both app targets.

extension ReadinessLevel {
    /// Calm, non-alarming tint per readiness band. Recovery days are indigo, never red.
    var tint: Color {
        switch self {
        case .strong: .green
        case .ready: .routeTeal
        case .easy: .orange
        case .recover: .indigo
        }
    }

    /// Short user-facing label.
    var displayName: LocalizedStringResource {
        switch self {
        case .strong: "Strong"
        case .ready: "Ready"
        case .easy: "Easy"
        case .recover: "Recover"
        }
    }
}

extension FeelingLevel {
    var displayName: LocalizedStringResource {
        switch self {
        case .veryTired: "Very tired"
        case .tired: "Tired"
        case .normal: "Normal"
        case .good: "Good"
        case .excellent: "Excellent"
        }
    }
}

extension SorenessArea {
    var displayName: LocalizedStringResource {
        switch self {
        case .legs: "Legs"
        case .back: "Back"
        case .knee: "Knee"
        case .shoulder: "Shoulder"
        case .general: "General"
        }
    }
}

extension ActivityType {
    var displayName: LocalizedStringResource {
        switch self {
        case .walking: "Walking"
        case .running: "Running"
        case .cycling: "Cycling"
        case .strength: "Strength"
        case .mobility: "Mobility"
        case .balance: "Balance"
        case .stretching: "Stretching"
        case .chairExercise: "Chair exercise"
        case .swimming: "Swimming"
        case .core: "Core"
        case .recovery: "Recovery"
        }
    }
}

extension OnboardingGoal {
    var displayName: LocalizedStringResource {
        switch self {
        case .walkMore: "Walk more"
        case .sleepBetter: "Sleep better"
        case .buildConsistency: "Build consistency"
        case .recoverSmarter: "Recover smarter"
        }
    }

    var systemImage: String {
        switch self {
        case .walkMore: "figure.walk"
        case .sleepBetter: "moon.zzz.fill"
        case .buildConsistency: "calendar.badge.checkmark"
        case .recoverSmarter: "heart.text.square.fill"
        }
    }

    var tint: Color {
        switch self {
        case .walkMore: BodyPilotColors.successGreen
        case .sleepBetter: BodyPilotColors.sleepIndigo
        case .buildConsistency: BodyPilotColors.warningOrange
        case .recoverSmarter: BodyPilotColors.coreBlue
        }
    }
}

extension WorkoutIntensity {
    var displayName: LocalizedStringResource {
        switch self {
        case .recovery: "Recovery"
        case .light: "Light"
        case .moderate: "Moderate"
        case .hard: "Hard"
        }
    }
}

extension FitnessGoal {
    var displayName: LocalizedStringResource {
        switch self {
        case .getActiveAgain: "Get active again"
        case .loseWeight: "Lose weight"
        case .walkingEndurance: "Improve walking endurance"
        case .buildStrength: "Build strength"
        case .improveMobility: "Improve mobility"
        case .improveBalance: "Improve balance"
        case .healthyAging: "Healthy aging"
        case .generalFitness: "General fitness"
        }
    }
}

extension ActivityFrequency {
    var displayName: LocalizedStringResource {
        switch self {
        case .beginner: "Just starting out"
        case .occasional: "Occasionally active"
        case .regular: "Regularly active"
        case .veryActive: "Very active"
        }
    }
}

extension EquipmentType {
    var displayName: LocalizedStringResource {
        switch self {
        case .none: "No equipment"
        case .resistanceBands: "Resistance bands"
        case .dumbbells: "Dumbbells"
        case .homeGym: "Home gym"
        case .fullGym: "Full gym"
        }
    }
}

extension CoachTone {
    var displayName: LocalizedStringResource {
        switch self {
        case .supportive: "Supportive"
        case .direct: "Direct"
        case .energetic: "Energetic"
        }
    }
}
